In [1]:
import pandas as pd

In [5]:
EXCEL_DATA = "building_data.xlsx"

sheet = pd.read_excel(EXCEL_DATA)#, sheet_name="Sheet1", names=[
#     "date_added",
#     "occupancy",
#     "lease_signed",
#     "building",
#     "building_class",
#     "city",
#     "deal_size",
#     "tenant",
#     "new_renewal_expansion",
#     "term",
#     "base_rent",
#     "rent_structure",
#     "esc",
#     "t_i",
#     "rent_abatement",
#     "tenant_broker",
#     "ll_broker",
#     "t_o",
#     "comments"])

sheet.head()

,Date Added,Occupancy,Lease Signed,Building,Building Class,City,Deal Size,Tenant,New/ Renewal/ Expansion,Term,Base Rent,Rent Structure,Esc.,T.I.,Rent Abatement,Tenant Broker,LL Broker,T/O,Comments
0,2016-05-10 00:00:00,2Q 2019,1Q 2016,Commerce Plaza\n2015 Spring Road,A,Oak Brook,18541,Sterigenics,Renewal,9 Yrs. 4 Mos.,$21.22 N,Net,3%,38,9 Mos. Gross,Studley,JLL,9.67,NaN
1,2017-04-26 00:00:00,1Q 2019,1Q 2017,Corporate Lakes IV\n2300 Cabot Drive,A-/B+,Lisle,13359,Ice Miller LP,Renewal,6 Yrs.,$14.00 N,Net,$.50,None,None,NaN,CBRE,10.25,NaN
2,2017-01-24 00:00:00,3Q 2018,1Q 2017,Westings Corp. Center\n2056 Westings Avenue,A,Naperville,25083,Wells Fargo,Relocation,10 Yrs. 10 Mos.,$16.50 N,Net,$.50,As Is,6 Mos. G,JLL,CBRE,11.52,Early Renewal/Expansion
3,2017-05-02 00:00:00,1Q 2018,2Q 2017,2 Mid America Plaza,A,Oakbrook Terrace,4434,King-Devick Test,New,6 Yrs.,$19.50 N,Net,3%,2,4 Mos. G,Bradford Platinum,CBRE,NaN,NaN
4,2017-05-16 00:00:00,4Q 2017,1Q 2017,999 Oakmont Lane,B,Westmont,5155,Adventist Health Partners,Renewal,3 Yrs.,$12.50 N,Net,$.50,As Is,None,CBRE,NAI,8.26,NaN

In [15]:
inp = input("Enter a category:")
list_of_inputs = inp.strip().split(",")
print(list_of_inputs)
custom_sheet = sheet[list_of_inputs]
# custom_sheet = sheet[["Building", "{}".format(str(inp))]]
custom_sheet.head()

Enter a category:City, Building, Deal Size

AttributeError: 'list' object has no attribute 'strip'